# Mirrored data from src/data/destinations.js

destinations_data = [
    # Philippines
    {
        "id": 1,
        "name": 'El Nido',
        "country": 'ph',
        "desc": 'Beach paradise',
        "description": 'El Nido is known for its stunning limestone cliffs, crystal-clear waters, and hidden lagoons. It is a gateway to the Bacuit Archipelago.',
        "rating": 4.8,
        "reviews": '1.2k',
        "location": 'Palawan',
        "image": '/assets/destinations/el_nido.png', # Placeholder path
        "price": '4,999',
        "highlights": ['Big Lagoon', 'Small Lagoon', 'Secret Beach', 'Seven Commandos Beach'],
        "itinerary": [
            'Day 1: Arrival and Town Exploration',
            'Day 2: Island Hopping Tour A (Big Lagoon, Secret Lagoon)',
            'Day 3: Island Hopping Tour C (Hidden Beach, Matinloc Shrine)',
            'Day 4: Relax at Nacpan Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'November to May',
        "crowdLevel": 'High',
        "tag": 'Must Visit',
        "estimatedCostPerDay": 5000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May']
    },
    {
        "id": 2,
        "name": 'Baguio City',
        "country": 'ph',
        "desc": 'Mountain Getaway',
        "description": 'The Summer Capital offers a cool climate, pine-scented air, and a vibrant arts scene. Perfect escape from the heat.',
        "rating": 4.6,
        "reviews": '950',
        "location": 'Benguet',
        "image": '/assets/destinations/baguio.png',
        "price": '3,200',
        "highlights": ['Burnham Park', 'Camp John Hay', 'Mines View Park', 'BenCab Museum'],
        "itinerary": [
            'Day 1: Arrival and Session Road walk',
            'Day 2: Burnham Park and Museum tour',
            'Day 3: Camp John Hay eco-trail',
            'Day 4: Strawberry Picking in La Trinidad',
            'Day 5: Departure'
        ],
        "bestTime": 'December to February',
        "crowdLevel": 'High',
        "tag": 'Popular',
        "estimatedCostPerDay": 3500,
        "bestTimeMonths": ['Dec', 'Jan', 'Feb']
    },
    {
        "id": 3,
        "name": 'Siargao',
        "country": 'ph',
        "desc": 'Surf & Chill',
        "description": 'The Surfing Capital. Famous for Cloud 9, coconut forests, and a laid-back island vibe.',
        "rating": 4.9,
        "reviews": '2k',
        "location": 'Surigao del Norte',
        "image": '/assets/destinations/siargao.png',
        "price": '5,500',
        "highlights": ['Cloud 9 Boardwalk', 'Magpupungko Rock Pools', 'Sugba Lagoon', 'Coconut View Deck'],
        "itinerary": [
            'Day 1: Arrival and Sunset at Cloud 9',
            'Day 2: Surfing lessons and Magpupungko',
            'Day 3: Land Tour (Maasin River)',
            'Day 4: Island Hopping (Naked, Daku, Guyam)',
            'Day 5: Departure'
        ],
        "bestTime": 'July to November',
        "crowdLevel": 'Medium',
        "tag": 'Surfer\'s Paradise',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Jul', 'Aug', 'Sep', 'Oct', 'Nov']
    },
    {
        "id": 4,
        "name": 'Vigan',
        "country": 'ph',
        "desc": 'Heritage City',
        "description": 'A UNESCO World Heritage site, famous for cobblestone streets and Spanish colonial architecture.',
        "rating": 4.7,
        "reviews": '780',
        "location": 'Ilocos Sur',
        "image": '/assets/destinations/vigan.png',
        "price": '4,250',
        "highlights": ['Calle Crisologo', 'Syquia Mansion', 'Bantay Bell Tower', 'Dancing Fountain'],
        "itinerary": [
            'Day 1: Arrival and Night Walk',
            'Day 2: Vigan Heritage Tour',
            'Day 3: Bantay Bell Tower',
            'Day 4: Empanada tasting',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'Medium',
        "tag": 'Heritage',
        "estimatedCostPerDay": 3000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 5,
        "name": 'Boracay',
        "country": 'ph',
        "desc": 'White Sand Beach',
        "description": 'World-famous powdery white sand and vibrant nightlife. Top beach destination.',
        "rating": 4.9,
        "reviews": '5k',
        "location": 'Aklan',
        "image": '/assets/destinations/boracay.png',
        "price": '6,000',
        "highlights": ['White Beach', 'Puka Shell Beach', 'Willy\'s Rock', 'Ariel\'s Point'],
        "itinerary": [
            'Day 1: Arrival and Sunset Sailing',
            'Day 2: Island Hopping',
            'Day 3: Water Sports',
            'Day 4: Relax at Puka Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'High',
        "tag": 'Classic',
        "estimatedCostPerDay": 6000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 6,
        "name": 'Cebu City',
        "country": 'ph',
        "desc": 'Queen City',
        "description": 'Rich history, modern city life, and accessible natural wonders like Kawasan Falls.',
        "rating": 4.7,
        "reviews": '1.5k',
        "location": 'Cebu',
        "image": '/assets/destinations/cebu.png',
        "price": '3,800',
        "highlights": ['Magellan\'s Cross', 'Temple of Leah', 'Kawasan Falls', 'Oslob Whale Sharks'],
        "itinerary": [
            'Day 1: City Tour',
            'Day 2: South Cebu Tour',
            'Day 3: Canyoneering',
            'Day 4: Mountain Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'January to April',
        "crowdLevel": 'Medium',
        "tag": 'Adventure',
        "estimatedCostPerDay": 4000,
        "bestTimeMonths": ['Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 7,
        "name": 'Bohol',
        "country": 'ph',
        "desc": 'Chocolate Hills',
        "description": 'Home to the iconic Chocolate Hills and Tarsiers. Nature lover\'s paradise.',
        "rating": 4.8,
        "reviews": '1.1k',
        "location": 'Bohol',
        "image": '/assets/destinations/bohol.png',
        "price": '4,500',
        "highlights": ['Chocolate Hills', 'Tarsier Sanctuary', 'Loboc River Cruise', 'Alona Beach'],
        "itinerary": [
            'Day 1: Arrival in Panglao',
            'Day 2: Countryside Tour',
            'Day 3: Loboc River Cruise',
            'Day 4: Island Hopping',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'Medium',
        "tag": 'Nature',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 8,
        "name": 'Coron',
        "country": 'ph',
        "desc": 'Island Hopping',
        "description": 'World War II wrecks, crystal-clear lakes, and stunning limestone karsts.',
        "rating": 4.9,
        "reviews": '1.8k',
        "location": 'Palawan',
        "image": '/assets/destinations/coron.png',
        "price": '5,200',
        "highlights": ['Kayangan Lake', 'Twin Lagoon', 'Maquinit Hot Spring', 'Skeleton Wreck'],
        "itinerary": [
            'Day 1: Mt. Tapyas',
            'Day 2: Coron Island Ultimate Tour',
            'Day 3: Reef and Wrecks',
            'Day 4: Hot Spring',
            'Day 5: Departure'
        ],
        "bestTime": 'November to May',
        "crowdLevel": 'Medium',
        "tag": 'Diving',
        "estimatedCostPerDay": 5500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May']
    },

    # India
    {
        "id": 101,
        "name": 'Goa',
        "country": 'in',
        "desc": 'Beach & Parties',
        "description": 'A blend of Indian and Portuguese cultures, famous for sun, sand, spices, and trance parties.',
        "rating": 4.7,
        "reviews": '3.5k',
        "location": 'Goa',
        "image": 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80&w=800',
        "price": '4,000',
        "highlights": ['Baga Beach', 'Fort Aguada', 'Dudhsagar Falls', 'Old Goa Churches'],
        "itinerary": [
            'Day 1: North Goa Beach Hopping',
            'Day 2: Heritage Tour in Old Goa',
            'Day 3: South Goa Relaxing',
            'Day 4: Dudhsagar Waterfalls Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'November to March',
        "crowdLevel": 'High',
        "tag": 'Party & Beach',
        "estimatedCostPerDay": 4000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },
    {
        "id": 102,
        "name": 'Jaipur',
        "country": 'in',
        "desc": 'The Pink City',
        "description": 'The capital of Rajasthan, known for its royal palaces, forts, and vibrant bazaars.',
        "rating": 4.8,
        "reviews": '2.1k',
        "location": 'Rajasthan',
        "image": 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80&w=800',
        "price": '3,500',
        "highlights": ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar'],
        "itinerary": [
            'Day 1: City Palace & Hawa Mahal',
            'Day 2: Amber Fort & Elephant Ride',
            'Day 3: Shopping in Johari Bazaar',
            'Day 4: Nahargarh Fort Sunset',
            'Day 5: Departure'
        ],
        "bestTime": 'October to March',
        "crowdLevel": 'Medium',
        "tag": 'Culture',
        "estimatedCostPerDay": 3500,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },
    {
        "id": 103,
        "name": 'Kerala',
        "country": 'in',
        "desc": 'God\'s Own Country',
        "description": 'Famous for its backwaters, tea plantations, and pristine beaches.',
        "rating": 4.9,
        "reviews": '1.9k',
        "location": 'Kerala',
        "image": 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=800',
        "price": '4,200',
        "highlights": ['Alleppey Houseboats', 'Munnar Tea Gardens', 'Varkala Beach', 'Periyar Wildlife'],
        "itinerary": [
            'Day 1: Arrival in Cochin',
            'Day 2: Munnar Tea Gardens',
            'Day 3: Thekkady Wildlife',
            'Day 4: Alleppey Houseboat Stay',
            'Day 5: Departure'
        ],
        "bestTime": 'September to March',
        "crowdLevel": 'Low',
        "tag": 'Nature',
        "estimatedCostPerDay": 4200,
        "bestTimeMonths": ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },

    # Vietnam
    {
        "id": 201,
        "name": 'Ha Long Bay',
        "country": 'vn',
        "desc": 'Emerald Waters',
        "description": 'Known for its emerald waters and thousands of towering limestone islands topped with rainforests.',
        "rating": 4.9,
        "reviews": '4.2k',
        "location": 'Quang Ninh',
        "image": 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=800',
        "price": '5,000',
        "highlights": ['Overnight Cruise', 'Sung Sot Cave', 'Ti Top Island', 'Kayaking'],
        "itinerary": [
            'Day 1: Hanoi to Ha Long, Board Cruise',
            'Day 2: Explore Caves & Kayaking',
            'Day 3: Morning Tai Chi & Return to Harbor',
            'Day 4: Hanoi Street Food Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'October to December',
        "crowdLevel": 'High',
        "tag": 'Nature',
        "estimatedCostPerDay": 5000,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec']
    },
    {
        "id": 202,
        "name": 'Hoi An',
        "country": 'vn',
        "desc": 'Ancient Town',
        "description": 'A well-preserved Ancient Town cut through with canals. Famous for its lanterns and tailoring.',
        "rating": 4.8,
        "reviews": '3.1k',
        "location": 'Quang Nam',
        "image": 'https://images.unsplash.com/photo-1557750255-c76072a7ae40?auto=format&fit=crop&q=80&w=800',
        "price": '3,800',
        "highlights": ['Ancient Town', 'Japanese Bridge', 'An Bang Beach', 'Basket Boat Ride'],
        "itinerary": [
            'Day 1: Walking Tour of Ancient Town',
            'Day 2: My Son Sanctuary',
            'Day 3: Cooking Class & Market Tour',
            'Day 4: Bicycle to Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'February to April',
        "crowdLevel": 'Medium',
        "tag": 'Heritage',
        "estimatedCostPerDay": 3800,
        "bestTimeMonths": ['Feb', 'Mar', 'Apr']
    },
    {
        "id": 203,
        "name": 'Da Nang',
        "country": 'vn',
        "desc": 'Modern Coastal',
        "description": 'Known for its sandy beaches and history as a French colonial port.',
        "rating": 4.7,
        "reviews": '2.5k',
        "location": 'Da Nang',
        "image": 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800',
        "price": '4,100',
        "highlights": ['Dragon Bridge', 'Marble Mountains', 'Ba Na Hills', 'My Khe Beach'],
        "itinerary": [
            'Day 1: City & Dragon Bridge',
            'Day 2: Ba Na Hills & Golden Hand Bridge',
            'Day 3: Marble Mountains',
            'Day 4: Relax at My Khe Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'February to May',
        "crowdLevel": 'Medium',
        "tag": 'City & Beach',
        "estimatedCostPerDay": 4100,
        "bestTimeMonths": ['Feb', 'Mar', 'Apr', 'May']
    },

    # Thailand
    {
        "id": 301,
        "name": 'Bangkok',
        "country": 'th',
        "desc": 'Vibrant Capital',
        "description": 'Known for ornate shrines and vibrant street life. The boat-filled Chao Phraya River feeds its network of canals.',
        "rating": 4.8,
        "reviews": '5.5k',
        "location": 'Central Thailand',
        "image": 'https://images.unsplash.com/photo-1590214652253-ab0d6df6c9a3?auto=format&fit=crop&q=80&w=800',
        "price": '4,500',
        "highlights": ['Grand Palace', 'Wat Arun', 'Chatuchak Market', 'Khao San Road'],
        "itinerary": [
            'Day 1: Grand Palace & Wat Phra Kaew',
            'Day 2: Wat Arun & River Cruise',
            'Day 3: Shopping at Chatuchak/Siam',
            'Day 4: Ayutthaya Day Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'November to February',
        "crowdLevel": 'High',
        "tag": 'Urban',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb']
    },
    {
        "id": 302,
        "name": 'Phuket',
        "country": 'th',
        "desc": 'Island Paradise',
        "description": 'Rainforested, mountainous island in the Andaman Sea, has some of Thailand’s most popular beaches.',
        "rating": 4.7,
        "reviews": '4.8k',
        "location": 'Phuket',
        "image": 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&q=80&w=800',
        "price": '5,500',
        "highlights": ['Patong Beach', 'Big Buddha', 'Phi Phi Islands Tour', 'Old Phuket Town'],
        "itinerary": [
            'Day 1: Arrive & Patong Nightlife',
            'Day 2: Phi Phi Islands Speedboat',
            'Day 3: Big Buddha & Wat Chalong',
            'Day 4: James Bond Island Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'High',
        "tag": 'Beach',
        "estimatedCostPerDay": 5500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 303,
        "name": 'Chiang Mai',
        "country": 'th',
        "desc": 'Northern Culture',
        "description": 'Founded in 1296, it was capital of the independent Lanna Kingdom until 1558.',
        "rating": 4.9,
        "reviews": '3.0k',
        "location": 'Northern Thailand',
        "image": 'https://images.unsplash.com/photo-1520336203114-1e03a95c373a?auto=format&fit=crop&q=80&w=800',
        "price": '3,800',
        "highlights": ['Doi Suthep', 'Sunday Night Market', 'Elephant Sanctuary', 'Old City Temples'],
        "itinerary": [
            'Day 1: Old City Temple Tour',
            'Day 2: Doi Suthep Mountain',
            'Day 3: Elephant Sanctuary Visit',
            'Day 4: Cooking Class & Night Market',
            'Day 5: Departure'
        ],
        "bestTime": 'October to February',
        "crowdLevel": 'Medium',
        "tag": 'Culture',
        "estimatedCostPerDay": 3800,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb']
    }
]
