
destinations_data = [
    # Philippines
    {
        "id": 1,
        "name": 'El Nido',
        "country": 'ph',
        "desc": 'Beach paradise',
        "description": 'El Nido is known for its stunning limestone cliffs, crystal-clear waters, and hidden lagoons. It is a gateway to the Bacuit Archipelago.',
        "rating": 4.8,
        "reviews": '1.2k',
        "location": 'Palawan',
        "image": '/assets/destinations/el_nido.png', # Placeholder path
        "price": '4,999',
        "highlights": ['Big Lagoon', 'Small Lagoon', 'Secret Beach', 'Seven Commandos Beach'],
        "itinerary": [
            'Day 1: Arrival and Town Exploration',
            'Day 2: Island Hopping Tour A (Big Lagoon, Secret Lagoon)',
            'Day 3: Island Hopping Tour C (Hidden Beach, Matinloc Shrine)',
            'Day 4: Relax at Nacpan Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'November to May',
        "crowdLevel": 'High',
        "tag": 'Must Visit',
        "estimatedCostPerDay": 5000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May']
    },
    {
        "id": 2,
        "name": 'Baguio City',
        "country": 'ph',
        "desc": 'Mountain Getaway',
        "description": 'The Summer Capital offers a cool climate, pine-scented air, and a vibrant arts scene. Perfect escape from the heat.',
        "rating": 4.6,
        "reviews": '950',
        "location": 'Benguet',
        "image": '/assets/destinations/baguio.png',
        "price": '3,200',
        "highlights": ['Burnham Park', 'Camp John Hay', 'Mines View Park', 'BenCab Museum'],
        "itinerary": [
            'Day 1: Arrival and Session Road walk',
            'Day 2: Burnham Park and Museum tour',
            'Day 3: Camp John Hay eco-trail',
            'Day 4: Strawberry Picking in La Trinidad',
            'Day 5: Departure'
        ],
        "bestTime": 'December to February',
        "crowdLevel": 'High',
        "tag": 'Popular',
        "estimatedCostPerDay": 3500,
        "bestTimeMonths": ['Dec', 'Jan', 'Feb']
    },
    {
        "id": 3,
        "name": 'Siargao',
        "country": 'ph',
        "desc": 'Surf & Chill',
        "description": 'The Surfing Capital. Famous for Cloud 9, coconut forests, and a laid-back island vibe.',
        "rating": 4.9,
        "reviews": '2k',
        "location": 'Surigao del Norte',
        "image": '/assets/destinations/siargao.png',
        "price": '5,500',
        "highlights": ['Cloud 9 Boardwalk', 'Magpupungko Rock Pools', 'Sugba Lagoon', 'Coconut View Deck'],
        "itinerary": [
            'Day 1: Arrival and Sunset at Cloud 9',
            'Day 2: Surfing lessons and Magpupungko',
            'Day 3: Land Tour (Maasin River)',
            'Day 4: Island Hopping (Naked, Daku, Guyam)',
            'Day 5: Departure'
        ],
        "bestTime": 'July to November',
        "crowdLevel": 'Medium',
        "tag": 'Surfer\'s Paradise',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Jul', 'Aug', 'Sep', 'Oct', 'Nov']
    },
    {
        "id": 4,
        "name": 'Vigan',
        "country": 'ph',
        "desc": 'Heritage City',
        "description": 'A UNESCO World Heritage site, famous for cobblestone streets and Spanish colonial architecture.',
        "rating": 4.7,
        "reviews": '780',
        "location": 'Ilocos Sur',
        "image": '/assets/destinations/vigan.png',
        "price": '4,250',
        "highlights": ['Calle Crisologo', 'Syquia Mansion', 'Bantay Bell Tower', 'Dancing Fountain'],
        "itinerary": [
            'Day 1: Arrival and Night Walk',
            'Day 2: Vigan Heritage Tour',
            'Day 3: Bantay Bell Tower',
            'Day 4: Empanada tasting',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'Medium',
        "tag": 'Heritage',
        "estimatedCostPerDay": 3000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 5,
        "name": 'Boracay',
        "country": 'ph',
        "desc": 'White Sand Beach',
        "description": 'World-famous powdery white sand and vibrant nightlife. Top beach destination.',
        "rating": 4.9,
        "reviews": '5k',
        "location": 'Aklan',
        "image": '/assets/destinations/boracay.png',
        "price": '6,000',
        "highlights": ['White Beach', 'Puka Shell Beach', 'Willy\'s Rock', 'Ariel\'s Point'],
        "itinerary": [
            'Day 1: Arrival and Sunset Sailing',
            'Day 2: Island Hopping',
            'Day 3: Water Sports',
            'Day 4: Relax at Puka Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'High',
        "tag": 'Classic',
        "estimatedCostPerDay": 6000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 6,
        "name": 'Cebu City',
        "country": 'ph',
        "desc": 'Queen City',
        "description": 'Rich history, modern city life, and accessible natural wonders like Kawasan Falls.',
        "rating": 4.7,
        "reviews": '1.5k',
        "location": 'Cebu',
        "image": '/assets/destinations/cebu.png',
        "price": '3,800',
        "highlights": ['Magellan\'s Cross', 'Temple of Leah', 'Kawasan Falls', 'Oslob Whale Sharks'],
        "itinerary": [
            'Day 1: City Tour',
            'Day 2: South Cebu Tour',
            'Day 3: Canyoneering',
            'Day 4: Mountain Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'January to April',
        "crowdLevel": 'Medium',
        "tag": 'Adventure',
        "estimatedCostPerDay": 4000,
        "bestTimeMonths": ['Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 7,
        "name": 'Bohol',
        "country": 'ph',
        "desc": 'Chocolate Hills',
        "description": 'Home to the iconic Chocolate Hills and Tarsiers. Nature lover\'s paradise.',
        "rating": 4.8,
        "reviews": '1.1k',
        "location": 'Bohol',
        "image": '/assets/destinations/bohol.png',
        "price": '4,500',
        "highlights": ['Chocolate Hills', 'Tarsier Sanctuary', 'Loboc River Cruise', 'Alona Beach'],
        "itinerary": [
            'Day 1: Arrival in Panglao',
            'Day 2: Countryside Tour',
            'Day 3: Loboc River Cruise',
            'Day 4: Island Hopping',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'Medium',
        "tag": 'Nature',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 8,
        "name": 'Coron',
        "country": 'ph',
        "desc": 'Island Hopping',
        "description": 'World War II wrecks, crystal-clear lakes, and stunning limestone karsts.',
        "rating": 4.9,
        "reviews": '1.8k',
        "location": 'Palawan',
        "image": '/assets/destinations/coron.png',
        "price": '5,200',
        "highlights": ['Kayangan Lake', 'Twin Lagoon', 'Maquinit Hot Spring', 'Skeleton Wreck'],
        "itinerary": [
            'Day 1: Mt. Tapyas',
            'Day 2: Coron Island Ultimate Tour',
            'Day 3: Reef and Wrecks',
            'Day 4: Hot Spring',
            'Day 5: Departure'
        ],
        "bestTime": 'November to May',
        "crowdLevel": 'Medium',
        "tag": 'Diving',
        "estimatedCostPerDay": 5500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May']
    },

    # India
    {
        "id": 101,
        "name": 'Goa',
        "country": 'in',
        "desc": 'Beach & Parties',
        "description": 'A blend of Indian and Portuguese cultures, famous for sun, sand, spices, and trance parties.',
        "rating": 4.7,
        "reviews": '3.5k',
        "location": 'Goa',
        "image": 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80&w=800',
        "price": '4,000',
        "highlights": ['Baga Beach', 'Fort Aguada', 'Dudhsagar Falls', 'Old Goa Churches'],
        "itinerary": [
            'Day 1: North Goa Beach Hopping',
            'Day 2: Heritage Tour in Old Goa',
            'Day 3: South Goa Relaxing',
            'Day 4: Dudhsagar Waterfalls Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'November to March',
        "crowdLevel": 'High',
        "tag": 'Party & Beach',
        "estimatedCostPerDay": 4000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },
    {
        "id": 102,
        "name": 'Jaipur',
        "country": 'in',
        "desc": 'The Pink City',
        "description": 'The capital of Rajasthan, known for its royal palaces, forts, and vibrant bazaars.',
        "rating": 4.8,
        "reviews": '2.1k',
        "location": 'Rajasthan',
        "image": 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80&w=800',
        "price": '3,500',
        "highlights": ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar'],
        "itinerary": [
            'Day 1: City Palace & Hawa Mahal',
            'Day 2: Amber Fort & Elephant Ride',
            'Day 3: Shopping in Johari Bazaar',
            'Day 4: Nahargarh Fort Sunset',
            'Day 5: Departure'
        ],
        "bestTime": 'October to March',
        "crowdLevel": 'Medium',
        "tag": 'Culture',
        "estimatedCostPerDay": 3500,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },
    {
        "id": 103,
        "name": 'Kerala',
        "country": 'in',
        "desc": 'God\'s Own Country',
        "description": 'Famous for its backwaters, tea plantations, and pristine beaches.',
        "rating": 4.9,
        "reviews": '1.9k',
        "location": 'Kerala',
        "image": 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=800',
        "price": '4,200',
        "highlights": ['Alleppey Houseboats', 'Munnar Tea Gardens', 'Varkala Beach', 'Periyar Wildlife'],
        "itinerary": [
            'Day 1: Arrival in Cochin',
            'Day 2: Munnar Tea Gardens',
            'Day 3: Thekkady Wildlife',
            'Day 4: Alleppey Houseboat Stay',
            'Day 5: Departure'
        ],
        "bestTime": 'September to March',
        "crowdLevel": 'Low',
        "tag": 'Nature',
        "estimatedCostPerDay": 4200,
        "bestTimeMonths": ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    },

    # Vietnam
    {
        "id": 201,
        "name": 'Ha Long Bay',
        "country": 'vn',
        "desc": 'Emerald Waters',
        "description": 'Known for its emerald waters and thousands of towering limestone islands topped with rainforests.',
        "rating": 4.9,
        "reviews": '4.2k',
        "location": 'Quang Ninh',
        "image": 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=800',
        "price": '5,000',
        "highlights": ['Overnight Cruise', 'Sung Sot Cave', 'Ti Top Island', 'Kayaking'],
        "itinerary": [
            'Day 1: Hanoi to Ha Long, Board Cruise',
            'Day 2: Explore Caves & Kayaking',
            'Day 3: Morning Tai Chi & Return to Harbor',
            'Day 4: Hanoi Street Food Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'October to December',
        "crowdLevel": 'High',
        "tag": 'Nature',
        "estimatedCostPerDay": 5000,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec']
    },
    {
        "id": 202,
        "name": 'Hoi An',
        "country": 'vn',
        "desc": 'Ancient Town',
        "description": 'A well-preserved Ancient Town cut through with canals. Famous for its lanterns and tailoring.',
        "rating": 4.8,
        "reviews": '3.1k',
        "location": 'Quang Nam',
        "image": 'https://images.unsplash.com/photo-1557750255-c76072a7ae40?auto=format&fit=crop&q=80&w=800',
        "price": '3,800',
        "highlights": ['Ancient Town', 'Japanese Bridge', 'An Bang Beach', 'Basket Boat Ride'],
        "itinerary": [
            'Day 1: Walking Tour of Ancient Town',
            'Day 2: My Son Sanctuary',
            'Day 3: Cooking Class & Market Tour',
            'Day 4: Bicycle to Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'February to April',
        "crowdLevel": 'Medium',
        "tag": 'Heritage',
        "estimatedCostPerDay": 3800,
        "bestTimeMonths": ['Feb', 'Mar', 'Apr']
    },
    {
        "id": 203,
        "name": 'Da Nang',
        "country": 'vn',
        "desc": 'Modern Coastal',
        "description": 'Known for its sandy beaches and history as a French colonial port.',
        "rating": 4.7,
        "reviews": '2.5k',
        "location": 'Da Nang',
        "image": 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&q=80&w=800',
        "price": '4,100',
        "highlights": ['Dragon Bridge', 'Marble Mountains', 'Ba Na Hills', 'My Khe Beach'],
        "itinerary": [
            'Day 1: City & Dragon Bridge',
            'Day 2: Ba Na Hills & Golden Hand Bridge',
            'Day 3: Marble Mountains',
            'Day 4: Relax at My Khe Beach',
            'Day 5: Departure'
        ],
        "bestTime": 'February to May',
        "crowdLevel": 'Medium',
        "tag": 'City & Beach',
        "estimatedCostPerDay": 4100,
        "bestTimeMonths": ['Feb', 'Mar', 'Apr', 'May']
    },

    # Thailand
    {
        "id": 301,
        "name": 'Bangkok',
        "country": 'th',
        "desc": 'Vibrant Capital',
        "description": 'Known for ornate shrines and vibrant street life. The boat-filled Chao Phraya River feeds its network of canals.',
        "rating": 4.8,
        "reviews": '5.5k',
        "location": 'Central Thailand',
        "image": 'https://images.unsplash.com/photo-1590214652253-ab0d6df6c9a3?auto=format&fit=crop&q=80&w=800',
        "price": '4,500',
        "highlights": ['Grand Palace', 'Wat Arun', 'Chatuchak Market', 'Khao San Road'],
        "itinerary": [
            'Day 1: Grand Palace & Wat Phra Kaew',
            'Day 2: Wat Arun & River Cruise',
            'Day 3: Shopping at Chatuchak/Siam',
            'Day 4: Ayutthaya Day Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'November to February',
        "crowdLevel": 'High',
        "tag": 'Urban',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb']
    },
    {
        "id": 302,
        "name": 'Phuket',
        "country": 'th',
        "desc": 'Island Paradise',
        "description": 'Rainforested, mountainous island in the Andaman Sea, has some of Thailand’s most popular beaches.',
        "rating": 4.7,
        "reviews": '4.8k',
        "location": 'Southern Thailand',
        "image": 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&q=80&w=800',
        "price": '5,500',
        "highlights": ['Patong Beach', 'Big Buddha', 'Phi Phi Islands Tour', 'Old Phuket Town'],
        "itinerary": [
            'Day 1: Arrive & Patong Nightlife',
            'Day 2: Phi Phi Islands Speedboat',
            'Day 3: Big Buddha & Wat Chalong',
            'Day 4: James Bond Island Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'High',
        "tag": 'Beach',
        "estimatedCostPerDay": 5500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 303,
        "name": 'Chiang Mai',
        "country": 'th',
        "desc": 'Northern Culture',
        "description": 'Founded in 1296, it was capital of the independent Lanna Kingdom until 1558.',
        "rating": 4.9,
        "reviews": '3.0k',
        "location": 'Northern Thailand',
        "image": 'https://images.unsplash.com/photo-1520336203114-1e03a95c373a?auto=format&fit=crop&q=80&w=800',
        "price": '3,800',
        "highlights": ['Doi Suthep', 'Sunday Night Market', 'Elephant Sanctuary', 'Old City Temples'],
        "itinerary": [
            'Day 1: Old City Temple Tour',
            'Day 2: Doi Suthep Mountain',
            'Day 3: Elephant Sanctuary Visit',
            'Day 4: Cooking Class & Night Market',
            'Day 5: Departure'
        ],
        "bestTime": 'October to February',
        "crowdLevel": 'Medium',
        "tag": 'Culture',
        "estimatedCostPerDay": 3800,
        "bestTimeMonths": ['Oct', 'Nov', 'Dec', 'Jan', 'Feb']
    },
    {
        "id": 304,
        "name": 'Udon Thani',
        "country": 'th',
        "desc": 'Isan Gateway',
        "description": 'A major regional hub in Isan, known for the Red Lotus Sea and Ban Chiang archaeological site.',
        "rating": 4.5,
        "reviews": '1.2k',
        "location": 'Northeastern Thailand (Isan)',
        "image": 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&q=80&w=800',
        "price": '3,000',
        "highlights": ['Red Lotus Sea', 'Ban Chiang', 'Nong Prajak Park', 'Wat Pa Phu Kon'],
        "itinerary": [
            'Day 1: City & Nong Prajak Park',
            'Day 2: Red Lotus Sea (Morning)',
            'Day 3: Ban Chiang Museum',
            'Day 4: Wat Pa Phu Kon',
            'Day 5: Departure'
        ],
        "bestTime": 'November to February',
        "crowdLevel": 'Low',
        "tag": 'Nature',
        "estimatedCostPerDay": 3000,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb']
    },
    {
        "id": 305,
        "name": 'Pattaya',
        "country": 'th',
        "desc": 'Eastern Beach',
        "description": 'A vibrant coastal city in the region, known for beaches, water sports, and nightlife.',
        "rating": 4.6,
        "reviews": '2.8k',
        "location": 'Eastern Thailand',
        "image": 'https://images.unsplash.com/photo-1598971861913-d3411a77d7b5?auto=format&fit=crop&q=80&w=800',
        "price": '4,800',
        "highlights": ['Walking Street', 'Sanctuary of Truth', 'Koh Larn', 'Nong Nooch Garden'],
        "itinerary": [
            'Day 1: Beach & Walking Street',
            'Day 2: Koh Larn Island Trip',
            'Day 3: Sanctuary of Truth',
            'Day 4: Water Park or Gardens',
            'Day 5: Departure'
        ],
        "bestTime": 'November to April',
        "crowdLevel": 'High',
        "tag": 'Beach',
        "estimatedCostPerDay": 4800,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr']
    },
    {
        "id": 306,
        "name": 'Kanchanaburi',
        "country": 'th',
        "desc": 'River Kwai',
        "description": 'Known for the Death Railway, bridge over the River Kwai, and Erawan National Park waterfalls.',
        "rating": 4.8,
        "reviews": '1.5k',
        "location": 'Western Thailand',
        "image": 'https://images.unsplash.com/photo-1593368228514-c10d3e5272a2?auto=format&fit=crop&q=80&w=800',
        "price": '3,500',
        "highlights": ['Erawan Waterfalls', 'Bridge over River Kwai', 'Death Railway', 'Hellfire Pass'],
        "itinerary": [
            'Day 1: Bridge & War Museum',
            'Day 2: Death Railway Train Ride',
            'Day 3: Erawan Waterfalls',
            'Day 4: Hellfire Pass',
            'Day 5: Departure'
        ],
        "bestTime": 'November to February',
        "crowdLevel": 'Medium',
        "tag": 'History',
        "estimatedCostPerDay": 3500,
        "bestTimeMonths": ['Nov', 'Dec', 'Jan', 'Feb']
    },
    # Spain
    {
        "id": 401,
        "name": 'Barcelona',
        "country": 'es',
        "desc": 'Art & Architecture',
        "description": 'The cosmopolitan capital of Spain’s Catalonia region, known for its art and architecture.',
        "rating": 4.8,
        "reviews": '3.2k',
        "location": 'Catalonia',
        "image": 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&q=80&w=800',
        "price": '6,500',
        "highlights": ['Sagrada Familia', 'Park Güell', 'Gothic Quarter', 'La Rambla'],
        "itinerary": [
            'Day 1: Sagrada Familia & Park Güell',
            'Day 2: Gothic Quarter & Picasso Museum',
            'Day 3: La Rambla & Boqueria Market',
            'Day 4: Beach Day at Barceloneta',
            'Day 5: Departure'
        ],
        "bestTime": 'May to June',
        "crowdLevel": 'High',
        "tag": 'Architecture',
        "estimatedCostPerDay": 6500,
        "bestTimeMonths": ['May', 'Jun', 'Sep', 'Oct']
    },
    {
        "id": 402,
        "name": 'Madrid',
        "country": 'es',
        "desc": 'Royal Capital',
        "description": 'Known for its elegant boulevards and expansive, manicured parks such as the Buen Retiro.',
        "rating": 4.7,
        "reviews": '2.8k',
        "location": 'Madrid',
        "image": 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&q=80&w=800',
        "price": '6,000',
        "highlights": ['Royal Palace', 'Prado Museum', 'Retiro Park', 'Plaza Mayor'],
        "itinerary": [
            'Day 1: Royal Palace & Almudena Cathedral',
            'Day 2: Prado Museum & Art Walk',
            'Day 3: Retiro Park & Crystal Palace',
            'Day 4: Shopping on Gran Vía',
            'Day 5: Departure'
        ],
        "bestTime": 'September to November',
        "crowdLevel": 'Medium',
        "tag": 'Culture',
        "estimatedCostPerDay": 6000,
        "bestTimeMonths": ['Sep', 'Oct', 'Nov', 'Mar', 'Apr', 'May']
    },
    # France
    {
        "id": 501,
        "name": 'Paris',
        "country": 'fr',
        "desc": 'City of Light',
        "description": 'France\'s capital, is a major European city and a global center for art, fashion, gastronomy and culture.',
        "rating": 4.9,
        "reviews": '6.5k',
        "location": 'Île-de-France',
        "image": 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=800',
        "price": '7,500',
        "highlights": ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Champs-Élysées'],
        "itinerary": [
            'Day 1: Eiffel Tower & Seine Cruise',
            'Day 2: Louvre Museum & Tuileries',
            'Day 3: Montmartre & Sacré-Cœur',
            'Day 4: Versailles Day Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'April to June',
        "crowdLevel": 'High',
        "tag": 'Romance',
        "estimatedCostPerDay": 7500,
        "bestTimeMonths": ['Apr', 'May', 'Jun', 'Sep', 'Oct']
    },
    {
        "id": 502,
        "name": 'Nice',
        "country": 'fr',
        "desc": 'French Riviera',
        "description": 'Capital of the Alpes-Maritimes department on the French Riviera, sits on the pebbly shores of the Baie des Anges.',
        "rating": 4.6,
        "reviews": '2.1k',
        "location": 'French Riviera',
        "image": 'https://images.unsplash.com/photo-1533646564613-2d17477c74c7?auto=format&fit=crop&q=80&w=800',
        "price": '7,000',
        "highlights": ['Promenade des Anglais', 'Castle Hill', 'Old Town (Vieux Nice)', 'Flower Market'],
        "itinerary": [
            'Day 1: Promenade des Anglais Walk',
            'Day 2: Old Town & Castle Hill',
            'Day 3: Day trip to Monaco',
            'Day 4: Beach & Relaxation',
            'Day 5: Departure'
        ],
        "bestTime": 'May to September',
        "crowdLevel": 'High',
        "tag": 'Beach',
        "estimatedCostPerDay": 7000,
        "bestTimeMonths": ['May', 'Jun', 'Jul', 'Aug', 'Sep']
    },
    # Japan
    {
        "id": 601,
        "name": 'Shinjuku (Tokyo)',
        "country": 'jp',
        "desc": 'Neon City',
        "description": 'A major commercial and administrative centre, housing the busiest railway station in the world.',
        "rating": 4.8,
        "reviews": '4.5k',
        "location": 'Kanto',
        "image": 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800',
        "price": '6,000',
        "highlights": ['Shinjuku Gyoen', 'Kabukicho', 'Tokyo Metropolitan Government Building', 'Omoide Yokocho'],
        "itinerary": [
            'Day 1: Arrival & Exploring Kabukicho',
            'Day 2: Shinjuku Gyoen National Garden',
            'Day 3: Shopping at Lumine/Takashimaya',
            'Day 4: Day trip to Mt. Takao',
            'Day 5: Departure'
        ],
        "bestTime": 'March to May',
        "crowdLevel": 'High',
        "tag": 'Urban',
        "estimatedCostPerDay": 6000,
        "bestTimeMonths": ['Mar', 'Apr', 'May', 'Oct', 'Nov']
    },
    {
        "id": 602,
        "name": 'Sapporo',
        "country": 'jp',
        "desc": 'Snow Capital',
        "description": 'Capital of Hokkaido, famous for its beer, skiing and annual Sapporo Snow Festival.',
        "rating": 4.7,
        "reviews": '3.2k',
        "location": 'Hokkaido',
        "image": 'https://images.unsplash.com/photo-1516243160216-9b575916f86c?auto=format&fit=crop&q=80&w=800',
        "price": '5,500',
        "highlights": ['Odori Park', 'Sapporo Beer Museum', 'Clock Tower', 'Susukino'],
        "itinerary": [
            'Day 1: Odori Park & Clock Tower',
            'Day 2: Beer Museum & Genghis Khan',
            'Day 3: Day trip to Otaru',
            'Day 4: Skiing or Moerenuma Park',
            'Day 5: Departure'
        ],
        "bestTime": 'December to February',
        "crowdLevel": 'High',
        "tag": 'Snow',
        "estimatedCostPerDay": 5500,
        "bestTimeMonths": ['Dec', 'Jan', 'Feb']
    },
    {
        "id": 603,
        "name": 'Kyoto',
        "country": 'jp',
        "desc": 'Cultural Heart',
        "description": 'Famous for its numerous classical Buddhist temples, gardens, imperial palaces, Shinto shrines and traditional wooden houses.',
        "rating": 4.9,
        "reviews": '6.0k',
        "location": 'Kansai (Kinki)',
        "image": 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800',
        "price": '5,800',
        "highlights": ['Fushimi Inari', 'Kinkaku-ji', 'Arashiyama Bamboo Grove', 'Gion District'],
        "itinerary": [
            'Day 1: Fushimi Inari Shrine',
            'Day 2: Kinkaku-ji & Arashiyama',
            'Day 3: Kiyomizu-dera & Gion',
            'Day 4: Nara Day Trip',
            'Day 5: Departure'
        ],
        "bestTime": 'October to November',
        "crowdLevel": 'High',
        "tag": 'Culture',
        "estimatedCostPerDay": 5800,
        "bestTimeMonths": ['Oct', 'Nov', 'Mar', 'Apr']
    },
    {
        "id": 604,
        "name": 'Osaka',
        "country": 'jp',
        "desc": 'Kitchen of Japan',
        "description": 'Known for its modern architecture, nightlife and hearty street food.',
        "rating": 4.8,
        "reviews": '5.1k',
        "location": 'Kansai (Kinki)',
        "image": 'https://images.unsplash.com/photo-1590554045860-34a0b507e411?auto=format&fit=crop&q=80&w=800',
        "price": '5,600',
        "highlights": ['Dotonbori', 'Osaka Castle', 'Universal Studios Japan', 'Umeda Sky Building'],
        "itinerary": [
            'Day 1: Dotonbori Food Tour',
            'Day 2: Osaka Castle & Umeda',
            'Day 3: Universal Studios Japan',
            'Day 4: Aquarium Kaiyukan',
            'Day 5: Departure'
        ],
        "bestTime": 'October to November',
        "crowdLevel": 'High',
        "tag": 'Food',
        "estimatedCostPerDay": 5600,
        "bestTimeMonths": ['Oct', 'Nov', 'Mar', 'Apr']
    },
    {
        "id": 605,
        "name": 'Hiroshima',
        "country": 'jp',
        "desc": 'City of Peace',
        "description": 'A modern city with a tragic past, known for the Peace Memorial Park and nearby Miyajima Island.',
        "rating": 4.7,
        "reviews": '3.8k',
        "location": 'Chugoku',
        "image": 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&q=80&w=800',
        "price": '5,000',
        "highlights": ['Peace Memorial Park', 'Itsukushima Shrine', 'Hiroshima Castle', 'Shukkei-en'],
        "itinerary": [
            'Day 1: Peace Memorial Museum & Park',
            'Day 2: Miyajima Island & Shrine',
            'Day 3: Hiroshima Castle & Garden',
            'Day 4: Okonomiyaki Village',
            'Day 5: Departure'
        ],
        "bestTime": 'October to November',
        "crowdLevel": 'Medium',
        "tag": 'History',
        "estimatedCostPerDay": 5000,
        "bestTimeMonths": ['Oct', 'Nov', 'Mar', 'Apr']
    },
    {
        "id": 606,
        "name": 'Shirakawa-go',
        "country": 'jp',
        "desc": 'Traditional Village',
        "description": 'Known for its traditional gassho-zukuri farmhouses, some of which are more than 250 years old.',
        "rating": 4.8,
        "reviews": '2.5k',
        "location": 'Chubu',
        "image": 'https://images.unsplash.com/photo-1545645366-07a82c65a0b1?auto=format&fit=crop&q=80&w=800',
        "price": '6,500',
        "highlights": ['Gassho-zukuri Houses', 'Shiroyama Viewpoint', 'Wada House', 'Myozenji Temple'],
        "itinerary": [
            'Day 1: Explore Village & Houses',
            'Day 2: Shiroyama Viewpoint',
            'Day 3: Takayama Day Trip',
            'Day 4: Local Craft Experience',
            'Day 5: Departure'
        ],
        "bestTime": 'January to February',
        "crowdLevel": 'High',
        "tag": 'Heritage',
        "estimatedCostPerDay": 6500,
        "bestTimeMonths": ['Jan', 'Feb', 'May', 'Oct']
    },
    {
        "id": 607,
        "name": 'Fukuoka',
        "country": 'jp',
        "desc": 'Ramen Capital',
        "description": 'Known for ancient temples, beaches, and modern shopping malls. Famous for Hakata ramen.',
        "rating": 4.6,
        "reviews": '2.9k',
        "location": 'Kyushu',
        "image": 'https://images.unsplash.com/photo-1555523912-706720d2d31c?auto=format&fit=crop&q=80&w=800',
        "price": '4,800',
        "highlights": ['Ohori Park', 'Fukuoka Castle', 'Canal City', 'Yatai Food Stalls'],
        "itinerary": [
            'Day 1: Ohori Park & Ruins',
            'Day 2: Canal City & Shopping',
            'Day 3: Dazaifu Tenmangu Shrine',
            'Day 4: Yatai Food Tour',
            'Day 5: Departure'
        ],
        "bestTime": 'March to May',
        "crowdLevel": 'Medium',
        "tag": 'Food',
        "estimatedCostPerDay": 4800,
        "bestTimeMonths": ['Mar', 'Apr', 'May', 'Oct', 'Nov']
    },
    {
        "id": 608,
        "name": 'Matsuyama',
        "country": 'jp',
        "desc": 'Hot Springs',
        "description": 'Famous for Dogo Onsen, one of Japan\'s oldest hot springs, and Matsuyama Castle.',
        "rating": 4.5,
        "reviews": '1.5k',
        "location": 'Shikoku',
        "image": 'https://images.unsplash.com/photo-1624268153372-51a8301c2787?auto=format&fit=crop&q=80&w=800',
        "price": '4,500',
        "highlights": ['Dogo Onsen', 'Matsuyama Castle', 'Ishiteji Temple', 'Botchan Train'],
        "itinerary": [
            'Day 1: Matsuyama Castle',
            'Day 2: Dogo Onsen Soak',
            'Day 3: Ishiteji Temple',
            'Day 4: Local Citrus Tasting',
            'Day 5: Departure'
        ],
        "bestTime": 'October to November',
        "crowdLevel": 'Low',
        "tag": 'Wellness',
        "estimatedCostPerDay": 4500,
        "bestTimeMonths": ['Oct', 'Nov', 'Mar', 'Apr']
    },
    {
        "id": 609,
        "name": 'Sendai',
        "country": 'jp',
        "desc": 'City of Trees',
        "description": 'The capital of Miyagi Prefecture and the largest city in the Tohoku region.',
        "rating": 4.6,
        "reviews": '1.2k',
        "location": 'Tohoku',
        "image": 'https://images.unsplash.com/photo-1505374828359-866efd420556?auto=format&fit=crop&q=80&w=800',
        "price": '4,600',
        "highlights": ['Zuihoden', 'Osaki Hachimangu', 'Matsushima Bay', 'Sendai Castle Site'],
        "itinerary": [
            'Day 1: Sendai Castle & Museum',
            'Day 2: Matsushima Bay Cruise',
            'Day 3: Zuihoden Mausoleum',
            'Day 4: Akiu Onsen',
            'Day 5: Departure'
        ],
        "bestTime": 'August',
        "crowdLevel": 'Medium',
        "tag": 'Nature',
        "estimatedCostPerDay": 4600,
        "bestTimeMonths": ['Aug', 'Oct', 'Nov']
    }
]
